# Configuration taken from this article:
# https://paperless.blog/dependabot-on-gitlab
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: 'realm'
      - dependency-name: 'nodejs-mobile-react-native'
